on: [push]

jobs:
  ckan-harvest-job:
    runs-on: ubuntu-latest
    name: CKAN Harvester
    steps:
      - name: Harvest external source
        id: harvest
        uses: datopian/github-actions-for-ckan@v1.9
        with:
          url-to-harvest: 'https://od.data.gov.sa/Data/api/3/action/package_search?start=10'